# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/legal_analyzer}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.url=${SPRING_FLYWAY_URL:${spring.datasource.url}}
spring.flyway.user=${SPRING_FLYWAY_USER:${spring.datasource.username}}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD:${spring.datasource.password}}
