package com.rafaelvianna.legalanalyzer.web;

import com.rafaelvianna.legalanalyzer.async.*;
import com.rafaelvianna.legalanalyzer.config.AppProperties;
import com.rafaelvianna.legalanalyzer.datajud.*;
import com.rafaelvianna.legalanalyzer.exception.DocumentTooLargeException;
import com.rafaelvianna.legalanalyzer.exception.PdfProcessingException;
import com.rafaelvianna.legalanalyzer.persistence.*;
import com.rafaelvianna.legalanalyzer.web.dto.ProcessoListaResponse;
import com.rafaelvianna.legalanalyzer.web.dto.specialized.AnaliseEspecializadaRequest;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.util.List;

@RestController @RequestMapping("/api/v1/processos")
public class ProcessoAnaliseController {
 private final AnaliseJobService jobService; private final AnaliseEspecializadaJobService especializadaService; private final DataJudInsightsService insightsService; private final ProcessoPersistenceService persistenceService; private final AnaliseEspecializadaPersistenceService especializadaPersistence; private final AppProperties properties;
 public ProcessoAnaliseController(AnaliseJobService jobService,AnaliseEspecializadaJobService especializadaService,DataJudInsightsService insightsService,ProcessoPersistenceService persistenceService,AnaliseEspecializadaPersistenceService especializadaPersistence,AppProperties properties){this.jobService=jobService;this.especializadaService=especializadaService;this.insightsService=insightsService;this.persistenceService=persistenceService;this.especializadaPersistence=especializadaPersistence;this.properties=properties;}
 @PostMapping(value="/analisar",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<AnaliseJobResponse> analisar(@RequestParam("arquivo") MultipartFile arquivo){validarArquivo(arquivo);return ResponseEntity.status(HttpStatus.ACCEPTED).body(jobService.iniciar(arquivo));}
 @GetMapping public ResponseEntity<List<ProcessoListaResponse>> listar(){return ResponseEntity.ok(persistenceService.listar().stream().map(p->{var s=especializadaPersistence.ultimaDaBase(p.getId());return new ProcessoListaResponse(p.getId(),p.getNomeArquivo(),p.getNumeroCnj(),p.getStatus().name(),p.getProgresso(),p.getEtapa(),p.getMensagem(),p.getCriadoEm(),p.getAtualizadoEm(),p.getRelatorioPdf()!=null,s==null?null:s.getId(),s==null?null:s.getStatus(),s==null?0:s.getProgresso(),s==null?null:s.getEtapa(),s!=null&&s.getRelatorioPdf()!=null);}).toList());}
 @GetMapping("/analises/{id}") public ResponseEntity<AnaliseJobResponse> consultar(@PathVariable String id){AnaliseJob job=jobService.buscar(id);return ResponseEntity.ok(AnaliseJobResponse.status(job,especializadaService.opcao(job)));}
 @GetMapping(value="/analises/{id}/arquivo-pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<byte[]> baixarArquivoPdf(@PathVariable String id){var processo=persistenceService.buscar(id);if(processo==null)return ResponseEntity.notFound().build();byte[] pdf=persistenceService.arquivoOriginal(id);if(pdf==null||pdf.length==0)return ResponseEntity.notFound().build();return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).contentLength(pdf.length).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+nomeArquivoPdf(processo.getNomeArquivo())+"\"").body(pdf);}
 @GetMapping(value="/analises/{id}/relatorio-pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<byte[]> baixarRelatorioPdf(@PathVariable String id){var processo=persistenceService.buscar(id);if(processo==null)return ResponseEntity.notFound().build();byte[] pdf=persistenceService.relatorio(id);if(pdf==null||pdf.length==0)return ResponseEntity.notFound().build();return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).contentLength(pdf.length).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+nomeRelatorio(processo.getNomeArquivo())+"\"").body(pdf);}
 @GetMapping("/analises/{id}/datajud") public ResponseEntity<DataJudInfo> consultarDataJud(@PathVariable String id){return ResponseEntity.ok(jobService.buscar(id).dataJud());}
 @GetMapping("/analises/{id}/datajud/auditoria") public ResponseEntity<DataJudAuditoria> consultarAuditoriaDataJud(@PathVariable String id){AnaliseJob job=jobService.buscar(id);return ResponseEntity.ok(DataJudAuditoria.de(job.dataJud(),job.resultado()==null?List.of():job.resultado().partes()));}
 @GetMapping("/analises/{id}/datajud/timeline") public ResponseEntity<DataJudTimelineAuditoria> consultarTimelineDataJud(@PathVariable String id){AnaliseJob job=jobService.buscar(id);if(job.resultado()==null)return ResponseEntity.ok(DataJudTimelineAuditoria.indisponivel(job.dataJud()));return ResponseEntity.ok(DataJudAuditoria.sincronizarTimeline(job.dataJud(),job.textoExtraido(),job.resultado().cronologia()));}
 @GetMapping("/analises/{id}/datajud/insights") public ResponseEntity<DataJudInsights> consultarInsightsDataJud(@PathVariable String id){return ResponseEntity.ok(insightsService.analisar(jobService.buscar(id).dataJud()));}
 @PostMapping(value="/analises/{id}/especializada",consumes=MediaType.APPLICATION_JSON_VALUE) public ResponseEntity<AnaliseEspecializadaJobResponse> analisarEspecializada(@PathVariable String id,@RequestBody(required=false) AnaliseEspecializadaRequest request){return ResponseEntity.status(HttpStatus.ACCEPTED).body(especializadaService.iniciar(id,request));}
 @GetMapping("/analises-especializadas/{id}") public ResponseEntity<AnaliseEspecializadaJobResponse> consultarEspecializada(@PathVariable String id){return ResponseEntity.ok(especializadaService.consultar(id));}
 @GetMapping("/analises-especializadas/{id}/relatorio-pdf") public ResponseEntity<byte[]> baixarRelatorioEspecializado(@PathVariable String id){byte[] pdf=especializadaService.relatorio(id);if(pdf==null||pdf.length==0)return ResponseEntity.notFound().build();return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).contentLength(pdf.length).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\"analise-especializada-"+id+".pdf\"").body(pdf);}
 @PostMapping(value="/health") public ResponseEntity<String> health(){return ResponseEntity.ok("OK");}
 private String nomeArquivoPdf(String nome){String base=nome==null?"processo":nome.replaceAll("(?i)\\.pdf$","");return base+".pdf";}
 private String nomeRelatorio(String nome){String base=nome==null?"processo":nome.replaceAll("(?i)\\.pdf$","");return base+"-relatorio.pdf";}
 private void validarArquivo(MultipartFile arquivo){if(arquivo==null||arquivo.isEmpty())throw new PdfProcessingException("Nenhum arquivo foi enviado. Envie um PDF no campo \"arquivo\".");String contentType=arquivo.getContentType();boolean pareceSerPdfPeloNome=arquivo.getOriginalFilename()!=null&&arquivo.getOriginalFilename().toLowerCase().endsWith(".pdf");if((contentType==null||!contentType.equalsIgnoreCase(MediaType.APPLICATION_PDF_VALUE))&&!pareceSerPdfPeloNome)throw new PdfProcessingException("O arquivo enviado precisa ser um PDF (application/pdf).");long tamanhoMaximo=properties.pdf().maxFileSizeBytes();if(arquivo.getSize()>tamanhoMaximo)throw new DocumentTooLargeException("Arquivo excede o tamanho máximo permitido de "+(tamanhoMaximo/1_000_000)+"MB.");}
}
